name: "Flake.lock: update Nix dependencies"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'

jobs:
  nix-flake-update:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix (with flakes support)
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Update flake.lock and create PR
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update Nix flake inputs"
          pr-labels: |
            dependencies
            automated
